baseURL = "https://wecfund.netlify.com"
disqusShortname = ""
googleAnalytics = "G-6LHS8LXMMF"
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Bigspring Light"
[markup.goldmark.renderer]
unsafe = true
